name = "Widgets"
uuid = "cc8bc4a8-27d6-5769-a93b-9d913e69aa62"
version = "0.6.2"

[deps]
Colors = "5ae59095-9a9b-59fe-a467-6f913c188581"
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
Observables = "510215fc-4207-5dde-b226-833fc4488ee2"
OrderedCollections = "bac558e1-5e72-5ebc-8fee-abe8a469f55d"

[compat]
InteractBase = ">=0.7.1"
Observables = ">=0.2.2"
WebIO = ">=0.3.1"
julia = "0.7, 1"

[extras]
InteractBase = "d3863d7c-f0c8-5437-a7b4-3ae773c01009"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
WebIO = "0f1e0344-ec1d-5b48-a673-e5cf874b6c29"

[targets]
test = ["InteractBase", "WebIO", "Test"]
